lib/olivetree_web/router.ex
defmodule OlivetreeWeb.Router do
  use OlivetreeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug OlivetreeWeb.Plugs.GuardianPipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", OlivetreeWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/login", LoginController, :new
    post "/login", LoginController, :create
    get "/login/:magic_token", LoginController, :callback
  end

  pipeline :authentication_required do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", OlivetreeWeb do
    # Use the default browser stack
    pipe_through [:browser, :authentication_required]
    get "/logout", LoginController, :destroy

    # scope "/admin", Admin, as: :admin do
    #   get "/offers/published", OfferController, :index_published
    #   get "/offers/pending", OfferController, :index_unpublished
    #   get "/offers/:slug/publish", OfferController, :publish
    #   get "/offers/:slug/send_twitter", OfferController, :send_twitter
    #   get "/offers/:slug/send_telegram", OfferController, :send_telegram
    #   get "/offers/:slug/edit", OfferController, :edit
    #   put "/offers/:slug/edit", OfferController, :update
    #   delete "/offers/:slug", OfferController, :delete
    # end
  # Other scopes may use custom stacks.
  # scope "/api", OlivetreeWeb do
  #   pipe_through :api
  end
end

lib/olivetree_web/views/shared_view.ex
defmodule Olivetree.SharedView do
  use OlivetreeWeb, :view

  # alias Olivetree.Web.OfferController
  alias OlivetreeWeb.PageController
  # alias Olivetree.Web.Telegram

  import Phoenix.Controller, only: [controller_module: 1, action_name: 1]

  def get_flash_messages(%Plug.Conn{} = conn) do
    conn
    |> Phoenix.Controller.get_flash()
    |> Map.values()
  end

  # def show_new_offer_button(conn) do
  #   current_controller = controller_module(conn)
  #   current_action = action_name(conn)

  #   case {current_controller, current_action} do
  #     {OfferController, :index} -> true
  #     {OfferController, :index_filtered} -> true
  #     {OfferController, :search} -> true
  #     {PageController, :about} -> true
  #     _ -> false
  #   end
  # end

  # def get_telegram_channel(), do: Telegram.get_channel()
end

lib/olivetree_web/templates/shared/_alerts.html.eex
<%= for message <- get_flash_messages(@conn) do %>
<div class="notification is-primary">
  <span class="delete">&times;</span>
  <%= raw(message) %>
</div>
<% end %>

lib/olivetree_web/templates/shared/_analytics.html.eex
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=testtest"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', '<%= Application.get_env(:olivetree, :analytics_id) %>');
</script>

lib/olivetree_web/templates/shared/_cookies.html.eex
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#388cc1",
      "text": "#fff"
    },
    "button": {
      "background": "#083c5d",
      "text": "#fff"
    }
  },
  "position": "bottom-right",
  "content": {
    "message": "<%= gettext("By using this website, you allow us to use some cookies to improve your experience and provide statistics") %>"
  }
})});
</script>

lib/olivetree_web/templates/shared/_footer.html.eex
<footer class="footer">
  <div class="container">
    <div class="columns is-desktop">
      <div class="column has-text-centered has-text-left-desktop">
        <p>
          <strong>
            <%= raw gettext("Vitae sapien lobortis, sagittis commodo augue tempor in hendrerit ac. Enim dolor commodo nullam in.") %>
          </strong>
        </p>
        <p><%= raw gettext("Ac in nunc eget aliquip taciti donec. Arcu eu mauris sociosqu venenatis, neque libero in, quisque vel ac blandit litora habitant, molestie ligula repellat ac nunc, lacus neque massa eu.") %></p>
      </div>
      <div class="column has-text-centered has-text-right-desktop">
        <%= raw gettext("lobortis") %> <%= raw gettext("Vitae sapien") %> <br>
        <%= raw gettext("dolor neque") %>
        |
        <%= raw gettext("aenean libero") %> <br>
        <%= raw gettext("mauris sociosqu") %> <br>
      </div>
    </div>
    <div class="content has-text-centered">

      <p>

      </p>
    </div>
  </div>
</footer>

lib/olivetree_web/templates/shared/_hero.html.eex
<section class="hero main is-info is-medium is-bold">
  <div class="hero-body particles-container">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= gettext("Lorem ipsum dolor sit amet") %>
      </h1>
      <h2 class="subtitle">
        <%= gettext("Phasellus quis vulputate mauris. Ut sit amet gravida dolor.") %>
      </h2>
      <%# <%= if (show_new_offer_button(@conn)) do %>
  <%# <%= link(gettext("Post a job offer!"), to: {:javascript, rest}, class: "button new-offer-btn is-primary is-large") %>
      <%# <% end %>
    </div>
    <div id="particles"></div>
  </div>
</section>
<div class="box cta">
  <p class="has-text-centered">
    <span class="tag is-danger"><%= gettext("NEW") %></span>&nbsp;
          <a href='https://t.me/#{get_telegram_channel()}' class='button is-small is-info is-rounded' target='_blank'>Join now!&nbsp;<i class='fab fa-telegram-plane'></i></a>
  </p>
</div>

lib/olivetree_web/templates/shared/_navbar.html.eex
<nav id="navbar" class="navbar is-transparent is-fixed-top is-primary">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="#">
        <%= gettext("Olivetree") %>
      </a>
      <span class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-start">
        <%= if !user_logged_in?(@conn) do %>
        <a class="navbar-item" href="/login"><%= gettext "Login" %></a>
        <% end %>
        <a class="navbar-item" href="/about"><%= gettext "About" %></a>
      </div>
      <div class="navbar-end">
        <%= if user_logged_in?(@conn) do %>
        <%= link(gettext("Log out"), to: login_path(@conn, :destroy), class: "navbar-item") %>
        <% end %>
        <%= if !user_logged_in?(@conn) do %>
        <a class="navbar-item" href="/login"><%= gettext "Sign Up" %></a>
        <% end %>

      </div>
    </div>
  </div>
</nav>